apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fastapi-get-href-10-websites-argocd-app-to-apps
  namespace: argocd
spec:
  description: App of apps fastapi-get-href-10-websites-argocd-app-to-apps.
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
