apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-get-href-10-websites-kustomize
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alvarolinarescabre/fastapi-get-href-10-websites-kustomize.git
    targetRevision: HEAD
    path: .
  destination:
    name: in-cluster
